### ISSUE TITLE
Make site more accessible 

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/nativesintech.org#73]

**Comment by arecvlohe** [comment]
One way this can be addressed is using a framework of components that are made with accessibility in mind.

**Comment by patcon** [comment]
In case you're collecting todos, realized that modifying the typed.js text might be an easy win -- It should maybe be hidden on screenreaders with `aria-hidden="true"`, since screenreaders try to read text changes, and I suspect typed.js might be noisy (my computer is a little too bogged down to confirm this with Mac Voiceover right now).

Could also add a static span with some subset of the more screenreader pronounceable "hellos", but [using `.visually-hidden`](https://a11yproject.com/posts/how-to-hide-content/) that that only screenreaders pick it up :)

**Comment by arecvlohe** [comment]
@patcon Thanks for the advice! Accessibility is a big undertaking if we want to do it right. In the coming weeks or so I am going to create a GitHub project to identify where/how we can make the site fully keyboard navigable, accessible, and color schemed in the appropriate way. It will be a huge effort at least to get it right so I am looking forward to scoping things out.

**Comment by patcon** [comment]
Totally. Fwiw, as someone who just recently started doing so, just openning voiceover (or any screenreader) and trying to browse the website, that helped me see past the abstract lens I'd developed from just reading articles and checklists over the years -- it's so much more intuitive to see the pain points than I expected..!

**Comment by arecvlohe** [comment]
https://react-spectrum.adobe.com/react-aria/index.html

**Comment by arecvlohe** [comment]
I've made the site as accessible as I can using semantic html and other best practices. I think for now we are in a good place.
